"""Constants used in the ipSAE calculation."""

LIS_PAE_CUTOFF = 12

RESIDUE_SET = {
    "ALA",
    "ARG",
    "ASN",
    "ASP",
    "CYS",
    "GLN",
    "GLU",
    "GLY",
    "HIS",
    "ILE",
    "LEU",
    "LYS",
    "MET",
    "PHE",
    "PRO",
    "SER",
    "THR",
    "TRP",
    "TYR",
    "VAL",
    "DA",
    "DC",
    "DT",
    "DG",
    "A",
    "C",
    "U",
    "G",
}

NUC_RESIDUE_SET = {"DA", "DC", "DT", "DG", "A", "C", "U", "G"}

CHAIN_COLOR = {
    "A": "magenta",
    "B": "marine",
    "C": "lime",
    "D": "orange",
    "E": "yellow",
    "F": "cyan",
    "G": "lightorange",
    "H": "pink",
    "I": "deepteal",
    "J": "forest",
    "K": "lightblue",
    "L": "slate",
    "M": "violet",
    "N": "arsenic",
    "O": "iodine",
    "P": "silver",
    "Q": "red",
    "R": "sulfur",
    "S": "purple",
    "T": "olive",
    "U": "palegreen",
    "V": "green",
    "W": "blue",
    "X": "palecyan",
    "Y": "limon",
    "Z": "chocolate",
}
